# Generated by Django 4.2.1 on 2023-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KediCins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('karakter', models.TextField()),
                ('fiziksel', models.TextField()),
                ('beslenme', models.TextField()),
                ('egitim', models.TextField()),
                ('saglik', models.TextField()),
                ('resim', models.FileField(null=True, upload_to='urunler/')),
            ],
        ),
    ]
